refined environment handling

diff --git a/bin/build b/bin/build
--- a/bin/build
+++ b/bin/build
@@ -3,17 +3,8 @@
 # DMC Build Script
 ########################################################################
 
-import() {
-	echo '#!/bin/bash' > "$FILE"
-	echo "$1" >> "$FILE"
-	. "$FILE"
-}
-
-parse() {
-	echo "$CONTAINER" > "$FILE"
-	JSON=$(jq -r 'keys[] as $k | . as $v | [($k | ascii_upcase), (.[$k] | tostring)] | join("=")' "$FILE")
-	import "$JSON"
-	rm "$FILE"
+base_exists() {
+	(( $(echo "$DOCKER_IMAGES" | grep "^$APPLICATION" | grep -c "$ENVIRONMENT") )) || return 1
 }
 
 build() {
@@ -21,18 +12,69 @@ build() {
 	bin/dmc -b -i "$IMAGE" -t "$TAG"
 }
 
+check_base() {
+	COUNT=0
+	for ENVIRONMENT in ${ENVIRONMENTS[@]}; do
+		[ -n "$VERBOSE" ] && echo "CHECK ENVIRONMENT: $ENVIRONMENT"
+		base_exists || (( COUNT++ ))
+	done
+	(( "$COUNT" )) && echo "FAIL: $COUNT base images missing"
+	return "$COUNT"
+}
+
+check_images() {
+	COUNT=0
+	for CONTAINER in ${CONTAINERS[@]}; do
+		IMAGE=$(echo "$CONTAINER" | sed 's;.*"image":"\([^,]*\)".*;\1;')
+		TAG=$(echo "$CONTAINER" | sed 's;.*"tag":"\([^,]*\)".*;\1;')
+		[ -n "$VERBOSE" ] && echo "CHECK IMAGE: $IMAGE:$TAG"
+		image_exists || (( COUNT++ ))
+	done
+	(( "$COUNT" )) && echo "FAIL: $COUNT dependencies missing"
+	return "$COUNT"
+}
+
+create() {
+	CONFIG=$(CONTAINER="$1" bin/import)
+	. "$CONFIG" && rm "$CONFIG"
+	validate && build
+}
+
+fail() {
+	echo "FAIL: $IMAGE:$TAG $1"
+}
+
+image_exists() {
+	(( $(echo "$DOCKER_IMAGES" | grep -c "^$IMAGE:$TAG\$") )) || return 1
+}
+
+initialize() {
+	for ENVIRONMENT in ${ENVIRONMENTS[@]}; do
+		echo
+		echo "INIT ENVIRONMENT: $ENVIRONMENT"
+		bin/dmc -b -i gurumojo -t "$ENVIRONMENT" 2>/dev/null
+	done
+}
+
 validate() {
+	[ -z "$IMAGE" ] && echo 'Error: $IMAGE is required'
+	[ -z "$TAG" ] && echo 'Error: $TAG is required'
 	[ -n "$IMAGE" ] && [ -n "$TAG" ] || return 1
+	(( $(echo "$DOCKER_IMAGES" | grep -c "^$IMAGE:$TAG\$") )) && fail "exists" && return 1
+	return 0
 }
 
 
-FILE=$(tempfile)
+[ -n "$VERBOSE" ] && echo "BUILDING..."
 
 # source configuration
 . bin/env
 
-# activate containers
+# verify dependencies
+check_base || initialize
+
+# build containers
 for CONTAINER in ${CONTAINERS[@]}; do
-	parse && validate && build 2>/dev/null || echo "FAIL: $CONTAINER"
+	create "$CONTAINER"
 done
 
diff --git a/bin/wake b/bin/wake
--- a/bin/wake
+++ b/bin/wake
@@ -3,35 +3,72 @@
 # DMC Restart Script
 ########################################################################
 
-import() {
-	echo '#!/bin/bash' > "$FILE"
-	echo "$1" >> "$FILE"
-	. "$FILE"
+exists() {
+	(( $(echo "$DOCKER_ACTIVE" | grep -c "$CONTAINER\$") )) || return 1
 }
 
-parse() {
-	echo "$CONTAINER" > "$FILE"
-	JSON=$(jq -r 'keys[] as $k | . as $v | [($k | ascii_upcase), (.[$k] | tostring)] | join("=")' "$FILE")
-	import "$JSON"
-	rm "$FILE"
+fail() {
+	echo "FAIL: $CONTAINER $1"
+}
+
+initialize() {
+	CONFIG=$(CONTAINER="$1" bin/import)
+	. "$CONFIG" && rm "$CONFIG"
+	validate && route
+}
+
+inspect() {
+	(( $(echo "$DOCKER_IMAGES" | grep -c "^$IMAGE:$TAG\$") )) && return 0
+	fail "base image missing" && return 1
 }
 
 restart() {
+	echo
+	echo "RESTART: $CONTAINER from $IMAGE:$TAG"
+	echo "bin/dmc -r -c $CONTAINER -i $IMAGE -p $PORT -t $TAG -v $VOLUME"
 	bin/dmc -r -c "$CONTAINER" -i "$IMAGE" -p "$PORT" -t "$TAG" -v "$VOLUME"
 }
 
+route() {
+	exists && running && fail "already running" && return 1
+	stopped && restart && return 0
+	start
+}
+
+running() {
+	(( $(echo "$RUNNING" | grep -c "$CONTAINER\$") )) || return 1
+}
+
+start() {
+	echo
+	echo "START: $CONTAINER from $IMAGE:$TAG"
+	echo "bin/dmc -a -c $CONTAINER -i $IMAGE -p $PORT -t $TAG -v $VOLUME"
+	bin/dmc -a -c "$CONTAINER" -i "$IMAGE" -p "$PORT" -t "$TAG" -v "$VOLUME"
+}
+
+stopped() {
+	running && return 1 || exists || return 1
+}
+
 validate() {
+	[ -z "$CONTAINER" ] && echo 'Error: $CONTAINER is required'
+	[ -z "$IMAGE" ] && echo 'Error: $IMAGE is required'
+	[ -z "$PORT" ] && echo 'Error: $PORT is required'
+	[ -z "$TAG" ] && echo 'Error: $TAG is required'
+	[ -z "$VOLUME" ] && echo 'Error: $VOLUME is required'
 	[ -n "$CONTAINER" ] && [ -n "$IMAGE" ] && [ -n "$PORT" ] && [ -n "$TAG" ] && [ -n "$VOLUME" ] || return 1
+	inspect || return 1
+	return 0
 }
 
 
-FILE=$(tempfile)
+[ -n "$VERBOSE" ] && echo "WAKING UP..."
 
 # source configuration
 . bin/env
 
 # activate containers
 for CONTAINER in ${CONTAINERS[@]}; do
-	parse && validate && restart &>/dev/null || echo "FAIL: $CONTAINER"
+	initialize "$CONTAINER"
 done
 
